services:
  backend:
    build:
      context: ./backend/app
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app
    environment:
      - PYTHONPATH=/app
    env_file:
      - ./backend/app/.env
    restart: unless-stopped
    depends_on:
      - postgres
      - migrate

  migrate:
    build:
      context: ./backend/app
      dockerfile: Dockerfile
    env_file:
      - ./backend/app/.env
    depends_on:
      - postgres
    command: [ "uv", "run", "alembic", "upgrade", "head" ]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped


  postgres:
    image: postgres:13.3
    env_file:
      - ./backend/app/.env
    ports:
      - "5432:5432"