"""add feedback column application

Revision ID: 43d4892b1544
Revises: 1722e1790137
Create Date: 2025-07-14 18:38:01.464920

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "43d4892b1544"
down_revision: Union[str, Sequence[str], None] = "1722e1790137"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "applications", sa.Column("feedback", sa.Text(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("applications", "feedback")
    # ### end Alembic commands ###
