"""add applications, project_member, edit projects

Revision ID: 843428e10d39
Revises: 9486dd2901de
Create Date: 2025-07-09 13:50:32.127176

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "843428e10d39"
down_revision: Union[str, Sequence[str], None] = "9486dd2901de"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "applications",
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.Date(), nullable=True),
        sa.Column("is_approved", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("project_id", "user_id"),
    )
    op.create_index(
        "ix_applications_project_user",
        "applications",
        ["project_id", "user_id"],
        unique=True,
    )
    op.create_table(
        "project_members",
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.Date(), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("project_id", "user_id"),
    )
    op.create_index(
        "ix_project_members_project_id_user_id",
        "project_members",
        ["project_id", "user_id"],
        unique=False,
    )
    op.add_column("projects", sa.Column("ceo_id", sa.Integer(), nullable=False))
    op.add_column("projects", sa.Column("is_opensource", sa.Boolean(), nullable=False))
    op.add_column("projects", sa.Column("is_dead", sa.Boolean(), nullable=False))
    op.create_foreign_key(None, "projects", "users", ["ceo_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "projects", type_="foreignkey")
    op.drop_column("projects", "is_dead")
    op.drop_column("projects", "is_opensource")
    op.drop_column("projects", "ceo_id")
    op.drop_index("ix_project_members_project_id_user_id", table_name="project_members")
    op.drop_table("project_members")
    op.drop_index("ix_applications_project_user", table_name="applications")
    op.drop_table("applications")
    # ### end Alembic commands ###
