"""remove level user field

Revision ID: 9486dd2901de
Revises: 4a5a08b74a58
Create Date: 2025-07-02 20:01:44.910592

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9486dd2901de"
down_revision: Union[str, Sequence[str], None] = "4a5a08b74a58"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "level")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("level", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    # ### end Alembic commands ###
