[project]
name = "app"
version = "0.1.0"
description = "ProjectOR Backend Application"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.115.12",
    "uvicorn>=0.34.3",
]
