name: Bakend prod

on:
  push:
    branches: [ main ]
    paths:
      - backend/**
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.BACKEND_PROD_SERVICE_ID }}
          api-key: ${{ secrets.BACKEND_PROD_API_KEY }}
          wait-for-success: true
