name: Ba—Åkend prod

on:
  push:
    branches: [ main ]
    paths:
      - backend/**
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install uv package manager
        run: |
          python -m pip install --upgrade pip
          pip install uv
        working-directory: backend/app
      - name: Install dependencies with uv
        run: |
          uv sync --locked --no-dev
        working-directory: backend/app
      - name: Run tests
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
          POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          uv run pytest --maxfail=1 --disable-warnings -v
        working-directory: backend/app
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.BACKEND_PROD_SERVICE_ID }}
          api-key: ${{ secrets.BACKEND_PROD_API_KEY }}
          wait-for-success: true
